### PR TITLE
Refactored styles to angular component.

### PR DESCRIPTION
**Pull request by Eraldo**

### CODE REVIEW

**Comment by Eraldo** [comment]
Please tell me if this is also working for you. :)

**Comment by doxiaodong** [comment]
Is this also solved that `.forRoot` usage? 
I think it is same as `no-style` import.

It's forbidden to use `forRoot` in a lazy module, In this repo, it just a config for the module.
You can use it for a workaround way. If you do not want to do this, I can add a `forChild` static method as `forRoot`.

I test lazy module in https://github.com/doxiaodong/ng2-simplemde/tree/lazy
Clone the lazy banch and `yarn && npm start`

**Comment by doxiaodong** [comment]
Maybe `styleUrls` is more reasonable than `no-style`.
But it's a breaking change.

**Comment by Eraldo** [comment]
I guess styleUrls is more conform with how angular intends to integrate css for components.
Which would prevent systems like I use from complaining about the css import.
What is your suggestion of how to deal with this?

**Comment by doxiaodong** [comment]
You are right. but I don't think ionic is good.  It's not a freedom of config.

**Comment by doxiaodong** [comment]
released, https://github.com/doxiaodong/ng2-simplemde/releases/tag/v1.2.0

**Comment by doxiaodong** [comment]
@Eraldo , I want to revert this for https://github.com/doxiaodong/ng2-simplemde/issues/4 .
I don't know how to fix that.

**Comment by Eraldo** [comment]
Okay.
Maybe we can get help from someone how has experience creating angular components to show us how to deal with these css files so that all cases are covered.

**Comment by doxiaodong** [comment]
Does ionic support `@import "~simplemde/dist/xxx.css"` in scss ?

**Comment by Eraldo** [comment]
Yes, I think it does.
I am away for a week.
I can report back next week if it solved my issue. :)

**Pull request merged**
